export const certs = [
  {
    title: "English Proficiency",
    description: "CEFR Level C2",
    issuer: "EF SET",
    image: "/assets/images/certs/ef-cefr.png",
    logo: "/assets/images/certs/ef-logo.png",
    url: "https://cert.efset.org/TkPafK",
  },
  {
    title: "Python INTRO",
    description: "Curso de Python para principiantes",
    issuer: "FIAP",
    image: "/assets/images/certs/fiap-python.jpg",
    logo: "/assets/images/certs/fiap-logo.png",
    url: "https://on.fiap.com.br/pluginfile.php/1/local_nanocourses/certificado_nanocourse/105724/2caef4566e5080406a2796d32448d6f3/certificado.png",
  },
  {
    title: "Node Basic",
    description: "Certificação por projeto de Node.js",
    issuer: "Hacker Rank",
    image: "/assets/images/certs/hacker-rank-node-basic.png",
    logo: "/assets/images/certs/hacker-rank-logo.png",
    url: "https://www.hackerrank.com/certificates/c530b5ef74ad",
  },
  {
    title: "AWS reStart Intermediate",
    description: "Curso de AWS reStart Intermediate",
    issuer: "Escola da Nuvem",
    image: "/assets/images/certs/aws-re-start.jpg",
    logo: "/assets/images/certs/escola-da-nuvem-logo.png",
    url: "https://www.hackerrank.com/certificates/c530b5ef74ad",
  },
  {
    title: "React Basic",
    description: "Certificação por projeto de React.js",
    issuer: "Hacker Rank",
    image: "/assets/images/certs/hacker-rank-react-basic.png",
    logo: "/assets/images/certs/hacker-rank-logo.png",
    url: "https://www.hackerrank.com/certificates/d541f8b23f5f",
  },
  {
    title: "JavaScript Basic",
    description: "Certificação por projeto de JavaScript",
    issuer: "Hacker Rank",
    image: "/assets/images/certs/hacker-rank-js-basic.png",
    logo: "/assets/images/certs/hacker-rank-logo.png",
    url: "https://www.hackerrank.com/certificates/c530b5ef74ad",
  },
  {
    title: "Desenvolvimento Web",
    description: "Certificação por BootCamp de Desenvolvimento Web",
    issuer: "Trybe",
    image: "/assets/images/certs/trybe-desenvolvimento-web.png",
    logo: "/assets/images/certs/trybe-logo.png",
    url: "https://www.credential.net/59f71ce8-ec93-4e5d-bcc9-02cec5843934#gs.4cef8z",
  },
  {
    title: "Interactive Websites",
    description: "Certificação por curso",
    issuer: "Codecademy",
    image: "/assets/images/certs/codecademy-interactive-websites.png",
    logo: "/assets/images/certs/codecademy-logo.png",
    url: "https://www.codecademy.com/profiles/jhonatec/certificates/36ae898a1d1c8524815305b2d1d2ebab",
  },
  {
    title: "Learn CSS",
    description: "Certificação por curso",
    issuer: "Codecademy",
    image: "/assets/images/certs/codecademy-learn-css.png",
    logo: "/assets/images/certs/codecademy-logo.png",
    url: "https://www.codecademy.com/profiles/jhonatec/certificates/9a5bb1fc45b4281af1fffec93b0aaf05",
  },
];
